import { Country } from "../types/country";

const countries: Record<number, Omit<Country, "id">> = {
  1: {
    nameTh: "ไทย",
    nameEn: "Thailand",
    slug: "thailand",
    cityCount: 0,
    countryCode: "th",
  },
  2: {
    nameTh: "กัมพูชา",
    nameEn: "Cambodia",
    slug: "cambodia",
    cityCount: 25,
    countryCode: "kh",
  },
  3: {
    nameTh: "เกาหลีใต้",
    nameEn: "South Korea",
    slug: "south-korea",
    cityCount: 18,
    countryCode: "kr",
  },
  4: {
    nameTh: "จอร์เจีย",
    nameEn: "Georgia",
    slug: "georgia",
    cityCount: 12,
    countryCode: "ga",
  },
  5: {
    nameTh: "ชิลี",
    nameEn: "Chile",
    slug: "chile",
    cityCount: 16,
    countryCode: "cl",
  },
  6: {
    nameTh: "เซเชลส์",
    nameEn: "Seychelles",
    slug: "seychelles",
    cityCount: 2,
    countryCode: "sc",
  },
  7: {
    nameTh: "ญี่ปุ่น",
    nameEn: "Japan",
    slug: "japan",
    cityCount: 49,
    countryCode: "jp",
  },
  8: {
    nameTh: "ไต้หวัน",
    nameEn: "Taiwan",
    slug: "taiwan",
    cityCount: 14,
    countryCode: "tw",
  },
  9: {
    nameTh: "ตุรกี",
    nameEn: "Turkey",
    slug: "turkey",
    cityCount: 82,
    countryCode: "tr",
  },
  10: {
    nameTh: "บรูไน",
    nameEn: "Brunei",
    slug: "brunei",
    cityCount: 4,
    countryCode: "bn",
  },
  11: {
    nameTh: "บราซิล",
    nameEn: "Brazil",
    slug: "brazil",
    cityCount: 48,
    countryCode: "br",
  },
  12: {
    nameTh: "บาห์เรน",
    nameEn: "Bahrain",
    slug: "bahrain",
    cityCount: 12,
    countryCode: "bh",
  },
  13: {
    nameTh: "ปานามา",
    nameEn: "Panama",
    slug: "panama",
    cityCount: 12,
    countryCode: "pa",
  },
  14: {
    nameTh: "เปรู",
    nameEn: "Peru",
    slug: "peru",
    cityCount: 26,
    countryCode: "pe",
  },
  15: {
    nameTh: "พม่า",
    nameEn: "Myanmar",
    slug: "myanmar",
    cityCount: 15,
    countryCode: "mm",
  },
  16: {
    nameTh: "ฟิลิปปินส์",
    nameEn: "Philippines",
    slug: "philippines",
    cityCount: 81,
    countryCode: "ph",
  },
  17: {
    nameTh: "มัลดีฟส์",
    nameEn: "Maldives",
    slug: "maldives",
    cityCount: 25,
    countryCode: "mv",
  },
  18: {
    nameTh: "มาเลเซีย",
    nameEn: "Malaysia",
    slug: "malaysia",
    cityCount: 22,
    countryCode: "my",
  },
  19: {
    nameTh: "มองโกเลีย",
    nameEn: "Mongolia",
    slug: "mongolia",
    cityCount: 22,
    countryCode: "mn",
  },
  20: {
    nameTh: "มาเก๊า",
    nameEn: "Macau",
    slug: "macau",
    cityCount: 8,
    countryCode: "mo",
  },
  21: {
    nameTh: "รัสเซีย",
    nameEn: "Russia",
    slug: "russia",
    cityCount: 74,
    countryCode: "ru",
  },
  22: {
    nameTh: "ลาว",
    nameEn: "Laos",
    slug: "laos",
    cityCount: 18,
    countryCode: "la",
  },
  23: {
    nameTh: "วานูอาตู",
    nameEn: "Vanuatu",
    slug: "vanuatu",
    cityCount: 6,
    countryCode: "vu",
  },
  24: {
    nameTh: "เวียดนาม",
    nameEn: "Vietnam",
    slug: "vietnam",
    cityCount: 67,
    countryCode: "vn",
  },
  25: {
    nameTh: "สิงคโปร์",
    nameEn: "Singapore",
    slug: "singapore",
    cityCount: 1,
    countryCode: "sg",
  },
  26: {
    nameTh: "แอฟริกาใต้",
    nameEn: "South Africa",
    slug: "south-africa",
    cityCount: 10,
    countryCode: "za",
  },
  27: {
    nameTh: "อินโดนีเซีย",
    nameEn: "Indonesia",
    slug: "indonesia",
    cityCount: 34,
    countryCode: "id",
  },
  28: {
    nameTh: "เอกวาดอร์",
    nameEn: "Ecuador",
    slug: "ecuador",
    cityCount: 24,
    countryCode: "ec",
  },
  29: {
    nameTh: "อาร์เจนตินา",
    nameEn: "Argentina",
    slug: "argentina",
    cityCount: 24,
    countryCode: "ar",
  },
  30: {
    nameTh: "ฮ่องกง",
    nameEn: "Hong Kong",
    slug: "hong-kong",
    cityCount: 1,
    countryCode: "hk",
  },
  31: {
    nameTh: "ยุโรป",
    nameEn: "Europe",
    slug: "europe",
    cityCount: 1,
    countryCode: "eu",
  },
  32: {
    nameTh: "ฝรั่งเศส",
    nameEn: "France",
    slug: "france",
    cityCount: 15,
    countryCode: "fr",
  },
  33: {
    nameTh: "เยอรมัน",
    nameEn: "Germany",
    slug: "germany",
    cityCount: 16,
    countryCode: "de",
  },
  34: {
    nameTh: "สวิตเซอร์แลนด์",
    nameEn: "Switzerland",
    slug: "switzerland",
    cityCount: 20,
    countryCode: "ch",
  },
  35: {
    nameTh: "อิตาลี",
    nameEn: "Italy",
    slug: "italy",
    cityCount: 19,
    countryCode: "it",
  },
  36: {
    nameTh: "ออสเตรีย",
    nameEn: "Austria",
    slug: "austria",
    cityCount: 6,
    countryCode: "at",
  },
  37: {
    nameTh: "ฮังการี",
    nameEn: "Hungary",
    slug: "hungary",
    cityCount: 22,
    countryCode: "hu",
  },
  38: {
    nameTh: "อินเดีย",
    nameEn: "India",
    slug: "india",
    cityCount: 34,
    countryCode: "in",
  },
  39: {
    nameTh: "จีน",
    nameEn: "China",
    slug: "china",
    cityCount: 31,
    countryCode: "cn",
  },
  40: {
    nameTh: "สกอตแลนด์",
    nameEn: "Scotland",
    slug: "scotland",
    cityCount: 22,
    countryCode: "gb-sct",
  },
  41: {
    nameTh: "โปรตุเกส",
    nameEn: "Portugal",
    slug: "portugal",
    cityCount: 17,
    countryCode: "pt",
  },
  42: {
    nameTh: "ไอซ์แลนด์",
    nameEn: "Iceland",
    slug: "iceland",
    cityCount: 25,
    countryCode: "is",
  },
  43: {
    nameTh: "เนเธอร์แลนด์",
    nameEn: "Netherlands",
    slug: "netherlands",
    cityCount: 12,
    countryCode: "nl",
  },
  44: {
    nameTh: "เบลเยียม",
    nameEn: "Belgium",
    slug: "belgium",
    cityCount: 31,
    countryCode: "be",
  },
  45: {
    nameTh: "สเปน",
    nameEn: "Spain",
    slug: "spain",
    cityCount: 22,
    countryCode: "es",
  },
  46: {
    nameTh: "เช็ก",
    nameEn: "Czech",
    slug: "czech",
    cityCount: 13,
    countryCode: "cz",
  },
  47: {
    nameTh: "อังกฤษ",
    nameEn: "England",
    slug: "england",
    cityCount: 46,
    countryCode: "gb-eng",
  },
  48: {
    nameTh: "สวีเดน",
    nameEn: "Sweden",
    slug: "sweden",
    cityCount: 21,
    countryCode: "se",
  },
  49: {
    nameTh: "นอร์เวย์",
    nameEn: "Norway",
    slug: "norway",
    cityCount: 10,
    countryCode: "no",
  },
  50: {
    nameTh: "เดนมาร์ก",
    nameEn: "Denmark",
    slug: "denmark",
    cityCount: 12,
    countryCode: "dk",
  },
  51: {
    nameTh: "จอร์แดน",
    nameEn: "Jordan",
    slug: "jordan",
    cityCount: 12,
    countryCode: "jo",
  },
  52: {
    nameTh: "ศรีลังกา",
    nameEn: "Sri Lanka",
    slug: "sri-lanka",
    cityCount: 10,
    countryCode: "lk",
  },
  53: {
    nameTh: "เวลส์",
    nameEn: "Wales",
    slug: "wales",
    cityCount: 6,
    countryCode: "gb-wls",
  },
  54: {
    nameTh: "สหรัฐอาหรับเอมิเรตส์",
    nameEn: "United Arab Emirates",
    slug: "united-arab-emirates",
    cityCount: 7,
    countryCode: "ae",
  },
  55: {
    nameTh: "สโลวีเนีย",
    nameEn: "Slovenia",
    slug: "slovenia",
    cityCount: 87,
    countryCode: "si",
  },
  56: {
    nameTh: "สาธารณรัฐโครเอเชีย",
    nameEn: "Republic of Croatia",
    slug: "republic-of-croatia",
    cityCount: 19,
    countryCode: "hr",
  },
  57: {
    nameTh: "นิวซีแลนด์",
    nameEn: "New Zealand",
    slug: "new-zealand",
    cityCount: 116,
    countryCode: "nz",
  },
  58: {
    nameTh: "สหรัฐอเมริกา",
    nameEn: "United States of America",
    slug: "united-states-of-america",
    cityCount: 63,
    countryCode: "us",
  },
  59: {
    nameTh: "โปแลนด์",
    nameEn: "Poland",
    slug: "poland",
    cityCount: 18,
    countryCode: "pl",
  },
  60: {
    nameTh: "แคนาดา",
    nameEn: "Canada",
    slug: "canada",
    cityCount: 49,
    countryCode: "ca",
  },
  61: {
    nameTh: "ออสเตรเลีย",
    nameEn: "Australia",
    slug: "australia",
    cityCount: 8,
    countryCode: "au",
  },
  62: {
    nameTh: "อาเซอร์ไบจาน",
    nameEn: "Azerbaijan",
    slug: "azerbaycan",
    cityCount: 62,
    countryCode: "az",
  },
  63: {
    nameTh: "โมร็อคโค",
    nameEn: "Morocco",
    slug: "morocco",
    cityCount: 69,
    countryCode: "ma",
  },
  64: {
    nameTh: "สโลวาเกีย",
    nameEn: "Slovakia",
    slug: "slovakia",
    cityCount: 8,
    countryCode: "sk",
  },
  65: {
    nameTh: "ภูฏาน",
    nameEn: "Bhutan",
    slug: "bhutan",
    cityCount: 19,
    countryCode: "bt",
  },
  66: {
    nameTh: "ฟินแลนด์",
    nameEn: "Finland",
    slug: "finland",
    cityCount: 19,
    countryCode: "fi",
  },
  67: {
    nameTh: "ลิทัวเนีย",
    nameEn: "Lithuania",
    slug: "lithuania",
    cityCount: 34,
    countryCode: "lt",
  },
  68: {
    nameTh: "ลัตเวีย",
    nameEn: "Latvia",
    slug: "latvia",
    cityCount: 31,
    countryCode: "lv",
  },
  69: {
    nameTh: "เอสโตเนีย",
    nameEn: "Estonia",
    slug: "estonia",
    cityCount: 15,
    countryCode: "ee",
  },
  70: {
    nameTh: "บัลแกเรีย",
    nameEn: "Bulgaria",
    slug: "bulgaria",
    cityCount: 1,
    countryCode: "bg",
  },
  71: {
    nameTh: "โรมาเนีย",
    nameEn: "Romania",
    slug: "romania",
    cityCount: 1,
    countryCode: "ro",
  },
  72: {
    nameTh: "แอลจีเรีย",
    nameEn: "Algeria",
    slug: "algeria",
    cityCount: 0,
    countryCode: "dz",
  },
  73: {
    nameTh: "ยูกันดา",
    nameEn: "Uganda",
    slug: "uganda",
    cityCount: 0,
    countryCode: "ug",
  },
  74: {
    nameTh: "รวันดา",
    nameEn: "Rwanda",
    slug: "rwanda",
    cityCount: 0,
    countryCode: "rw",
  },
  75: {
    nameTh: "เซอร์เบีย",
    nameEn: "Serbia",
    slug: "serbia",
    cityCount: 0,
    countryCode: "rs",
  },
  76: {
    nameTh: "มอนเตเนโกร",
    nameEn: "Montenegro",
    slug: "montenegro",
    cityCount: 0,
    countryCode: "me",
  },
  77: {
    nameTh: "ตูนีเซีย",
    nameEn: "Tunisia",
    slug: "tunisia",
    cityCount: 0,
    countryCode: "tn",
  },
  78: {
    nameTh: "กรีซ",
    nameEn: "Greece",
    slug: "greece",
    cityCount: 16,
    countryCode: "gr",
  },
  79: {
    nameTh: "ไอร์แลนด์",
    nameEn: "Ireland",
    slug: "ireland",
    cityCount: 0,
    countryCode: "ie",
  },
  80: {
    nameTh: "อียิปต์",
    nameEn: "Egypt",
    slug: "egypt",
    cityCount: 7,
    countryCode: "eg",
  },
  81: {
    nameTh: "เนปาล",
    nameEn: "Nepal",
    slug: "nepal",
    cityCount: 1,
    countryCode: "np",
  },
  82: {
    nameTh: "อิหร่าน",
    nameEn: "Iran",
    slug: "iran",
    cityCount: 1,
    countryCode: "ir",
  },
  83: {
    nameTh: "กรีนแลนด์",
    nameEn: "Greenland",
    slug: "greenland",
    cityCount: 1,
    countryCode: "gl",
  },
  84: {
    nameTh: "อิสราเอล",
    nameEn: "Israel",
    slug: "israel",
    cityCount: 3,
    countryCode: "il",
  },
  85: {
    nameTh: "ไซปรัส",
    nameEn: "Cyprus",
    slug: "cyprus",
    cityCount: 6,
    countryCode: "cy",
  },
  86: {
    nameTh: "คาซัคสถาน",
    nameEn: "Kazakhstan",
    slug: "kazakhstan",
    cityCount: 4,
    countryCode: "kz",
  },
  87: {
    nameTh: "สาธารณรัฐอาร์มีเนีย",
    nameEn: "Republic of Armenia",
    slug: "armenia",
    cityCount: 1,
    countryCode: "",
  },
  88: {
    nameTh: "ลักเซมเบิร์ก",
    nameEn: "Luxembourg",
    slug: "luxembourg",
    cityCount: 0,
    countryCode: "",
  },
};

export function getCityCount(countryId: number): number {
  if (countries[countryId]) {
    return countries[countryId].cityCount ?? 0;
  }

  return 0;
}

export function getCountrySlug(countryId: number): string | null {
  if (countries[countryId]) {
    return countries[countryId].slug;
  }

  return null;
}

export function getCountryNameTH(countryId: number): string | null {
  if (countries[countryId]) {
    return countries[countryId].nameTh;
  }

  return null;
}

export function getAllCountry(): Country[] {
  const data: Country[] = [];
  for (const key in countries) {
    data.push({
      id: +key,
      nameTh: countries[key].nameTh,
      nameEn: countries[key].nameEn,
      slug: countries[key].slug,
      countryCode: countries[key].countryCode,
    });
  }

  return data;
}
