export type Country = {
  name_th: string;
  name_en: string;
  country_code: string;
  slug: string;
};

export const asiaContinent: Country[] = [
  {
    name_th: "กัมพูชา",
    name_en: "Cambodia",
    country_code: "kh",
    slug: "cambodia",
  },
  {
    name_th: "คาซัคสถาน",
    name_en: "Kazakhstan",
    country_code: "KZ",
    slug: "kazakhstan",
  },
  {
    name_th: "จอร์แดน",
    name_en: "Jordan",
    country_code: "JO",
    slug: "jordan",
  },
  {
    name_th: "จีน",
    name_en: "China",
    country_code: "cn",
    slug: "china",
  },
  {
    name_th: "ญี่ปุ่น",
    name_en: "Japan",
    country_code: "jp",
    slug: "japan",
  },
  {
    name_th: "บรูไน",
    name_en: "Brunei",
    country_code: "bn",
    slug: "brunei",
  },
  {
    name_th: "บาห์เรน",
    name_en: "Bahrain",
    country_code: "bh",
    slug: "bahrain",
  },
  {
    name_th: "พม่า",
    name_en: "Myanmar",
    country_code: "mm",
    slug: "myanmar",
  },
  {
    name_th: "ฟิลิปปินส์",
    name_en: "Philippines",
    country_code: "ph",
    slug: "philippines",
  },
  {
    name_th: "ภูฏาน",
    name_en: "Bhutan",
    country_code: "bt",
    slug: "bhutan",
  },
  {
    name_th: "มองโกเลีย",
    name_en: "Mongolia",
    country_code: "mn",
    slug: "mongolia",
  },
  {
    name_th: "มัลดีฟส์",
    name_en: "Maldives",
    country_code: "mv",
    slug: "maldives",
  },
  {
    name_th: "มาเก๊า",
    name_en: "Macau",
    country_code: "mo",
    slug: "macau",
  },
  {
    name_th: "มาเลเซีย",
    name_en: "Malaysia",
    country_code: "my",
    slug: "malaysia",
  },
  {
    name_th: "ลาว",
    name_en: "Laos",
    country_code: "la",
    slug: "laos",
  },
  {
    name_th: "ศรีลังกา",
    name_en: "Sri Lanka",
    country_code: "LK",
    slug: "sri-lanka",
  },
  {
    name_th: "สหรัฐอาหรับเอมิเรตส์",
    name_en: "United Arab Emirates",
    country_code: "AE",
    slug: "united-arab-emirates",
  },
  {
    name_th: "สิงคโปร์",
    name_en: "Singapore",
    country_code: "sg",
    slug: "singapore",
  },
  {
    name_th: "อาเซอร์ไบจาน",
    name_en: "Azerbaijan",
    country_code: "az",
    slug: "azerbaycan",
  },
  {
    name_th: "อินเดีย",
    name_en: "India",
    country_code: "in",
    slug: "india",
  },
  {
    name_th: "อินโดนีเซีย",
    name_en: "Indonesia",
    country_code: "id",
    slug: "indonesia",
  },
  {
    name_th: "อิสราเอล",
    name_en: "Israel",
    country_code: "IL",
    slug: "israel",
  },
  {
    name_th: "อิหร่าน",
    name_en: "Iran",
    country_code: "IR",
    slug: "iran",
  },
  {
    name_th: "ฮ่องกง",
    name_en: "Hong Kong",
    country_code: "hk",
    slug: "hong-kong",
  },
  {
    name_th: "เกาหลีใต้",
    name_en: "South Korea",
    country_code: "kr",
    slug: "south-korea",
  },
  {
    name_th: "เนปาล",
    name_en: "Nepal",
    country_code: "NP",
    slug: "nepal",
  },
  {
    name_th: "เวียดนาม",
    name_en: "Vietnam",
    country_code: "vn",
    slug: "vietnam",
  },
  {
    name_th: "ไต้หวัน",
    name_en: "Taiwan",
    country_code: "tw",
    slug: "taiwan",
  },
  {
    name_th: "ไทย",
    name_en: "Thailand",
    country_code: "th",
    slug: "thailand",
  },
];
export const europeContinent: Country[] = [
  {
    name_th: "กรีซ",
    name_en: "Greece",
    country_code: "GR",
    slug: "greece",
  },
  {
    name_th: "จอร์เจีย",
    name_en: "Georgia",
    country_code: "ge",
    slug: "georgia",
  },
  {
    name_th: "ตุรกี",
    name_en: "Turkey",
    country_code: "tr",
    slug: "turkey",
  },
  {
    name_th: "นอร์เวย์",
    name_en: "Norway",
    country_code: "no",
    slug: "norway",
  },
  {
    name_th: "บัลแกเรีย",
    name_en: "Bulgaria",
    country_code: "BG",
    slug: "bulgaria",
  },
  {
    name_th: "ฝรั่งเศส",
    name_en: "France",
    country_code: "fr",
    slug: "france",
  },
  {
    name_th: "ฟินแลนด์",
    name_en: "Finland",
    country_code: "fi",
    slug: "finland",
  },
  {
    name_th: "มอนเตเนโกร",
    name_en: "Montenegro",
    country_code: "ME",
    slug: "montenegro",
  },
  {
    name_th: "ยุโรป",
    name_en: "Europe",
    country_code: "EU",
    slug: "europe",
  },
  {
    name_th: "รัสเซีย",
    name_en: "Russia",
    country_code: "ru",
    slug: "russia",
  },
  {
    name_th: "ลัตเวีย",
    name_en: "Latvia",
    country_code: "lv",
    slug: "latvia",
  },
  {
    name_th: "ลิทัวเนีย",
    name_en: "Lithuania",
    country_code: "lt",
    slug: "lithuania",
  },
  {
    name_th: "สกอตแลนด์",
    name_en: "Scotland",
    country_code: "gb-sct",
    slug: "scotland",
  },
  {
    name_th: "สวิตเซอร์แลนด์",
    name_en: "Switzerland",
    country_code: "ch",
    slug: "switzerland",
  },
  {
    name_th: "สวีเดน",
    name_en: "Sweden",
    country_code: "se",
    slug: "sweden",
  },
  {
    name_th: "สาธารณรัฐโครเอเชีย",
    name_en: "Republic of Croatia",
    country_code: "HR",
    slug: "republic-of-croatia",
  },
  {
    name_th: "สเปน",
    name_en: "Spain",
    country_code: "es",
    slug: "spain",
  },
  {
    name_th: "สโลวาเกีย",
    name_en: "Slovakia",
    country_code: "SK",
    slug: "slovakia",
  },
  {
    name_th: "สโลวีเนีย",
    name_en: "Slovenia",
    country_code: "SI",
    slug: "slovenia",
  },
  {
    name_th: "ออสเตรีย",
    name_en: "Austria",
    country_code: "at",
    slug: "austria",
  },
  {
    name_th: "อังกฤษ",
    name_en: "England",
    country_code: "gb-eng",
    slug: "england",
  },
  {
    name_th: "อิตาลี",
    name_en: "Italy",
    country_code: "it",
    slug: "italy",
  },
  {
    name_th: "ฮังการี",
    name_en: "Hungary",
    country_code: "hu",
    slug: "hungary",
  },
  {
    name_th: "เช็ก",
    name_en: "Czech",
    country_code: "cz",
    slug: "czech",
  },
  {
    name_th: "เซอร์เบีย",
    name_en: "Serbia",
    country_code: "RS",
    slug: "serbia",
  },
  {
    name_th: "เดนมาร์ก",
    name_en: "Denmark",
    country_code: "dk",
    slug: "denmark",
  },
  {
    name_th: "เนเธอร์แลนด์",
    name_en: "Netherlands",
    country_code: "nl",
    slug: "netherlands",
  },
  {
    name_th: "เบลเยียม",
    name_en: "Belgium",
    country_code: "be",
    slug: "belgium",
  },
  {
    name_th: "เยอรมัน",
    name_en: "Germany",
    country_code: "de",
    slug: "germany",
  },
  {
    name_th: "เวลส์",
    name_en: "Wales",
    country_code: "gb-wls",
    slug: "wales",
  },
  {
    name_th: "เอสโตเนีย",
    name_en: "Estonia",
    country_code: "ee",
    slug: "estonia",
  },
  {
    name_th: "โปรตุเกส",
    name_en: "Portugal",
    country_code: "pt",
    slug: "portugal",
  },
  {
    name_th: "โปแลนด์",
    name_en: "Poland",
    country_code: "pl",
    slug: "poland",
  },
  {
    name_th: "โรมาเนีย",
    name_en: "Romania",
    country_code: "RO",
    slug: "romania",
  },
  {
    name_th: "ไซปรัส",
    name_en: "Cyprus",
    country_code: "CY",
    slug: "cyprus",
  },
  {
    name_th: "ไอซ์แลนด์",
    name_en: "Iceland",
    country_code: "is",
    slug: "iceland",
  },
  {
    name_th: "ไอร์แลนด์",
    name_en: "Ireland",
    country_code: "IE",
    slug: "ireland",
  },
];
export const otherContinent: Country[] = [
  {
    name_th: "กรีนแลนด์",
    name_en: "Greenland",
    country_code: "GL",
    slug: "greenland",
  },
  {
    name_th: "ชิลี",
    name_en: "Chile",
    country_code: "cl",
    slug: "chile",
  },
  {
    name_th: "ตูนีเซีย",
    name_en: "Tunisia",
    country_code: "TN",
    slug: "tunisia",
  },
  {
    name_th: "นิวซีแลนด์",
    name_en: "New Zealand",
    country_code: "NZ",
    slug: "new-zealand",
  },
  {
    name_th: "บราซิล",
    name_en: "Brazil",
    country_code: "br",
    slug: "brazil",
  },
  {
    name_th: "ปานามา",
    name_en: "Panama",
    country_code: "pa",
    slug: "panama",
  },
  {
    name_th: "ยูกันดา",
    name_en: "Uganda",
    country_code: "UG",
    slug: "uganda",
  },
  {
    name_th: "รวันดา",
    name_en: "Rwanda",
    country_code: "RW",
    slug: "rwanda",
  },
  {
    name_th: "วานูอาตู",
    name_en: "Vanuatu",
    country_code: "vu",
    slug: "vanuatu",
  },
  {
    name_th: "สหรัฐอเมริกา",
    name_en: "United States of America",
    country_code: "us",
    slug: "united-states-of-america",
  },
  {
    name_th: "ออสเตรเลีย",
    name_en: "Australia",
    country_code: "au",
    slug: "australia",
  },
  {
    name_th: "อาร์เจนตินา",
    name_en: "Argentina",
    country_code: "ar",
    slug: "argentina",
  },
  {
    name_th: "อียิปต์",
    name_en: "Egypt",
    country_code: "EG",
    slug: "egypt",
  },
  {
    name_th: "เซเชลส์",
    name_en: "Seychelles",
    country_code: "sc",
    slug: "seychelles",
  },
  {
    name_th: "เปรู",
    name_en: "Peru",
    country_code: "pe",
    slug: "peru",
  },
  {
    name_th: "เอกวาดอร์",
    name_en: "Ecuador",
    country_code: "ec",
    slug: "ecuador",
  },
  {
    name_th: "แคนาดา",
    name_en: "Canada",
    country_code: "ca",
    slug: "canada",
  },
  {
    name_th: "แอฟริกาใต้",
    name_en: "South Africa",
    country_code: "za",
    slug: "south-africa",
  },
  {
    name_th: "แอลจีเรีย",
    name_en: "Algeria",
    country_code: "dz",
    slug: "algeria",
  },
  {
    name_th: "โมร็อคโค",
    name_en: "Morocco",
    country_code: "ma",
    slug: "morocco",
  },
];
